### ISSUE TITLE
Getting a complete vector of Theta estimates from Package LTM

### ISSUE THREAD

**Issue by Sohnia** [drizopoulos/ltm#11]
I am using package LTM to estimate a Rasch model:
irtestimates <- rasch(binRasch)
theta.est <- factor.scores(irtestimates,method="EAP")

The problem is that this does not return a vector of ALL the theta  
estimates, rather it gives me a summary of theta estimates
associated  with each response pattern in my data along with the number of
times  each response pattern occurs.  Any ideas on how to get the
complete vector of theta estimates? Thanks,

Such as Science data in ltm, its length is 392, but the length factor.scores(Science,method="EAP") returns is 298.

**Comment by drizopoulos** [comment]
You can use `factor.scores(irtestimates, resp.patterns = binRasch)`.
