### ISSUE TITLE
Could ltm deal with mix-format tests?

### ISSUE THREAD

**Issue by Shaojie-tw** [drizopoulos/ltm#12]
Hi Rizopoulos,

Recently I'm doing some analysis with mixed-format tests, including dichotomous items and polytomous items. I see that ltm can handle 3PL model and GR model. But I cannot find relevant function to deal with mixed-format tests. So, is there any functions that could handle this problem in ltm? Thanks a lot!

**Comment by drizopoulos** [comment]
Functions grm() and gpcm() work for both dichotomous and polytomous items.

**Comment by Shaojie-tw** [comment]
> Functions grm() and gpcm() work for both dichotomous and polytomous items.
> 
> 
> 
> From: Shaojie-tw <notifications@github.com>
> Sent: Thursday, July 16, 2020 4:39 AM
> To: drizopoulos/ltm <ltm@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [drizopoulos/ltm] Could ltm deal with mix-format tests? (#12)
> 
> 
> Hi Rizopoulos,
> 
> Recently I'm doing some analysis with mixed-format tests, including dichotomous items and polytomous items. I see that ltm can handle 3PL model and GR model. But I cannot find relevant function to deal with mixed-format tests. So, is there any functions that could handle this problem in ltm? Thanks a lot!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2Fltm%2Fissues%2F12&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C4bb8908dbdc541d252fa08d829316d45%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637304639574265428&sdata=ggodge1PL%2FINp2ZBeLbT%2B%2BjXUC7jCPsdhCJ2A15M9ns%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADE7TT37NJCOZVQZFNFSGDDR3ZR5BANCNFSM4O3L7DTQ&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C4bb8908dbdc541d252fa08d829316d45%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637304639574265428&sdata=1rToC1aHeotdybbUe9lzIgaqDiJt2VZ7LVgci12dR3E%3D&reserved=0>.

Thanks for your reply. I have used grm() function to calibrate dichotomous and polytomous items simultaneously by treating  dichotomous one as a special case of polytomous ones successfully.
Further, I have another question. How is the accuracy and stability of the performance of ltm for mix-format test calibration compared with other package or software, such as mirt and Parscale? Thanks!
