### ISSUE TITLE
Expose `f` function created inside of `information` function

### ISSUE THREAD

**Issue by SethPoulsen** [drizopoulos/ltm#15]
There have been a few times I have wanted to access the `f` function that is defined inside of `information` (https://github.com/drizopoulos/ltm/blob/master/R/information.R) so that I could, e.g. calculate the information and stderr at a particular ability level, or solve a system of equations to find out at what ability level the information level drops beneath a certain threshold. 

When I've done this before, I've just copy pasted the source code to define the function myself.

Would you accept a pull request that makes it easier to access this function? for example, by passing a particular argument to `information`, it will just create the `f` function and then return it?

Thanks for your consideration and thanks for the awesome package!

**Comment by drizopoulos** [comment]
Yes, this is fine.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
