### ISSUE TITLE
Applying scaling factor d (1.7) to apply the logistic item response model

### ISSUE THREAD

**Issue by state-o-flux** [drizopoulos/ltm#16]
Hi Dr.Rizopoulos,

I'm wondering if there is any way to apply the scaling factor d to the item response models in ltm. Specifically I'm working with gpcm as I have dichotomous and polytomous items.

**Comment by drizopoulos** [comment]
It is not clear what you exactly mean.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by state-o-flux** [comment]
I've read that IRT models can scale their discrimination parameter by a factor of 1.7 in order to estimate the logistic item response model (as opposed to the normal ogive item response model). I'm wondering if there is a way to apply this to gpcm. I've noticed that the optim and nlminb functions both have parameters that can scale their optimization routines and wonder if it's possible to implement into the model writ large.

**Comment by drizopoulos** [comment]
No, unfortunately, this will not be possible in gpcm().
