### ISSUE TITLE
no package "itm" in the R

### ISSUE THREAD

**Issue by yua1234** [drizopoulos/ltm#17]
I could not find "Itm" in the R package list. I would appreciate it if you could tell me how to install it.

**Comment by drizopoulos** [comment]
It is ltm not itm



From: yua1234 ***@***.***>
Sent: Thursday, April 29, 2021 7:54 AM
To: drizopoulos/ltm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/ltm] no package "itm" in the R (#17)


I could not find "Itm" in the R package list. I would appreciate it if you could tell me how to install it.

-

**Comment by yua1234** [comment]
Thank you for your reply.
I apologize for mistakenly referring to "Itm" as "itm" in the title, but when I try to install with the latest version of R (4.0.5), I get an error. Also, I can't find "Itm" in the package list.

===
> install.packages("Itm")
 パッケージを ‘C:/Users/yu/Documents/R/win-library/4.0’ 中にインストールします 
 (‘lib’ が指定されていないため) 
 --- このセッションで使うために、CRAN のミラーサイトを選んでください --- 
 警告メッセージ: 
package ‘Itm’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
>
