### ISSUE TITLE
no "Itm" in the package list

### ISSUE THREAD

**Issue by yua1234** [drizopoulos/ltm#18]
I try to install with the latest version of R (4.0.5), I get an error. Also, I can't find "Itm" in the package list.

===

install.packages("Itm")
パッケージを ‘C:/Users/yu/Documents/R/win-library/4.0’ 中にインストールします
(‘lib’ が指定されていないため)
--- このセッションで使うために、CRAN のミラーサイトを選んでください ---
警告メッセージ:
package ‘Itm’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by frankier** [comment]
It works for me. Maybe you need to upgrade your version of R?
