### ISSUE TITLE
Factor scores computation with Multiple Imputation fails

### ISSUE THREAD

**Issue by tpaskhalis** [drizopoulos/ltm#2]
I've been trying to compare the results of different computation methods for factor scoring of 2-parameter IRT model and Multiple Imputation failed. When I used the example from the documentation it also resulted in the following error:
```
> fit <- ltm(Abortion ~ z1)
> factor.scores(fit, method = "MI", B = 20) # Multiple Imputation
Error in FUN(X[[i]], ...) : 'dimnames' must be a list
``` 

The issue seems to be with the lines [58-59](https://github.com/drizopoulos/ltm/blob/e167b436e7ffb9e46021df4ac12e7676d8fd3f76/R/fscores.l.R#L58-L59) in `fscores.l.R`

Instead of:
```
        scores.B <- lapply(1:B, array, data = 0, dim = c(nx, factors))
        hes.B <- lapply(1:B, array, data = 0, dim = c(factors, factors, nx))
```
I think it should be something like:
```
scores.B <- lapply(1:B, function(x) x <- array(data = 0, dim = c(nx, factors)))
hes.B <- lapply(1:B, function(x) x <- array(data = 0, dim = c(factors, factors, nx)))
```

The same issue applies to line [72](https://github.com/drizopoulos/ltm/blob/e167b436e7ffb9e46021df4ac12e7676d8fd3f76/R/fscores.l.R#L72)

**Comment by drizopoulos** [comment]
Thanks for reporting this. I've committed a new version that resolves this.
