### ISSUE TITLE
IRT fitting to externally supplied ability score

### ISSUE THREAD

**Issue by treestalker** [drizopoulos/ltm#4]
I'm doing a data project on tests that are only partially multiple choice. For some tests I've been able to use ltm quite successfully by using the gpcm with one question being the score on the long answer, but for some it's failed. How hard would it be to allow IRT fitting for an externally supplied ability score, or do you mind if I try to implement it?

**Comment by drizopoulos** [comment]
The current implementation does not allow for that. Of course, I don't mind if you'd like to implement this.
